# Generated by Django 2.2.24 on 2022-11-08 14:26

from django.db import migrations

def is_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    old_buildings = Flat.objects.filter(construction_year__lt=2015)
    old_buildings.update(new_building=False)
    new_buildings = Flat.objects.exclude(construction_year__lt=2015)
    new_buildings.update(new_building=True)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(is_new_building)
    ]
