# Generated by Django 2.2.24 on 2022-11-08 14:26

from django.db import migrations

def is_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if not flat.new_building:
            flat.new_building = flat.construction_year >= 2015
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(is_new_building)
    ]
