# Generated by Django 2.2.24 on 2022-11-09 15:26

from django.db import migrations
import phonenumbers


def format_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if not flat.owner_pure_phone:
            flat.owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20221109_1249'),
    ]

    operations = [
        migrations.RunPython(format_phonenumber)
    ]
