# Generated by Django 2.2.24 on 2022-11-10 15:24

from django.db import migrations


def create_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.filter(owners=None).iterator():
        owner, _ = Owner.objects.get_or_create(name=flat.owner, defaults={
            'phonenumber': flat.owners_phonenumber,
            'normilized_phonenumber': flat.owner_pure_phone
        })
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(create_owner)
    ]
